name: quick test

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.py'
      - '**.pyx'
      - '**.pxd'
      - '.github/workflows/quick_test.yml'
      - 'pyproject.toml'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install Python
        uses: actions/setup-python@v2
      - name: load cached Python installation
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: lint-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: install linters
        run: pip install oitnb
      - name: lint with oitnb
        run: oitnb . --check
  test:
    needs: lint
    name: quick test
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: install Python
        uses: actions/setup-python@v2
      - name: load cached Python installation
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: install dependencies
        run: pip install ".[testing]"
      - name: run tests
        run: pytest
